title: Tszyan Chan's Homepage
page-top-title: Tszyan Chan
top-section-bg-text: Journalism and Communication
home-subtitle: Tszyan Chan&ensp;|&ensp;陈梓茵
copyright-text: '&copy; Sen Li 2023-2025. All Rights Reserved.'
